author: 10102
name: RedstoneDisabler
description: Enable/Disable redstone via Region Flag
depend: [WorldGuard, WorldEdit, WGCustomFlags]
main: me.insom.redstonedisabler.OWHRedstoneDisabler
version: 0.1